%YAML 1.2
---
api:
  name: "accounts-eapi"
  host: "0.0.0.0"
  port:  "8081"
  basepath: "/api/*"
  apiId: "19128528"
  layer: "experience"
  
accounts_papi:
  host: "ma-accounts-papi-v1-dev.us-e2.cloudhub.io" 
  path: "/api/accounts"
  connectiontiontimeout: "30000"
  responsetimeout: "20000"
  reconnectionretry: "3"
  reconnectionfrequency: "2000"
  
accounts_sfdc_sys_api:
  host: "ma-accounts-sfdc-sapi-v1-dev.us-e2.cloudhub.io"
  path: "/api/accounts"
  connectiontiontimeout: "30000"
  responsetimeout: "20000"
  reconnectionretry: "3"
  reconnectionfrequency: "2000"
  
  
error:
  errorDescription: Error occurred, please refer application logs for more details
  
errorMessage:
  BAD_REQUEST: BAD_REQUEST
  NOT_FOUND: NOT_FOUND
  METHOD_NOT_ALLOWED: METHOD_NOT_ALLOWED
  NOT_ACCEPTABLE: NOT_ACCEPTABLE
  UNSUPPORTED_MEDIA: UNSUPPORTED_MEDIA
  NOT_IMPLEMENTED: NOT_IMPLEMENTED
  CUSTOM_SERVICE_ERROR: CUSTOM_SERVICE_ERROR
  ANY: INTERNAL_SERVER_ERROR

errorCode:
  BAD_REQUEST: "400"
  NOT_FOUND: "404"
  METHOD_NOT_ALLOWED: "405"
  NOT_ACCEPTABLE: "406"
  UNSUPPORTED_MEDIA: "415"
  NOT_IMPLEMENTED: "501"
  CUSTOM_SERVICE_ERROR: "400"
  ANY: "500"  
 