#%RAML 1.0 DataType
displayName: create account response 
type: object
additionalProperties: true
properties:
  id: 
   type: string 
   required: true  
  status:
   type: number 
   required: true
  message:
   type: string 
   required: true

 