#%RAML 1.0 ResourceType
      usage: Use this resourceType to represent only a get method of item
      description: A  single <<resourcePathName|!uppercamelcase>>
      get:
        description: |
          Get  <<resourcePathName|!uppercamelcase>>,
          optionally filtered