#%RAML 1.0 ResourceType
      usage: Use this resourceType to represent only a post method of item
      description: A  single <<resourcePathName|!uppercamelcase>>
      post:
        description: |
          Post  <<resourcePathName|!uppercamelcase>>,
          optionally filtered