#%RAML 1.0 Trait

headers:
  client_id:
    type: string
    required: true
  client_secret:
    type: string
    required: true 
  client_name:
    type: string
    required: false
  grant_type:
    type: string
    required: true
  Authorization: 
    displayName: Authorization
    description: OAuth authentication base 64 encoded string
    type: string
    required: true    