#%RAML 1.0 Trait
queryParameters:
  page:
    description: page
    type: integer
    default: 1
    example: 1
    minimum: 1
    required: false
  limit:
    description: Limit number of items to be retrieved in a single request to <<maxItems>>.
    type: integer
    default: 10
    example: 10
    maximum: <<maxItems>>
    required: false