#%RAML 1.0 Trait
description: account common request headers
headers: 
  channel:
    type: string
    required: false
    example: "mobile"
  correlationId:
    type: string  
    required: true   
    example: "test12345"